### PR TITLE
Inline Google Fonts, improve body font

### PR DESCRIPTION
**Pull request by konklone**
Remove a third party ping and improve performance, through the magic of [`webfont-dl`](https://github.com/mmastrac/webfont-dl).

For reference: https://github.com/18F/18f.gsa.gov/pull/805

### CODE REVIEW

**Comment by konklone** [comment]
Oh, this also makes a font change to the main body! It moves the site from Times New Roman for body text to Average. Previously, only the headlines were Average. 

Before:

screenshot from 2015-05-10 23 51 32

After:

screenshot from 2015-05-10 23 51 11

**Comment by JoshData** [comment]
Mmmmm ok.

**Comment by konklone** [comment]
I'll take that as a go.

**Comment by JoshData** [comment]
Yeah and actually following that "mmmm":

https://github.com/if-then-fund/if.then.fund/commit/7bf3efa241524c519b48e034850d7dc4f9c2ad89

**Pull request merged**
