### PR TITLE
Version 2: Best practices around licensing of open government data

### PR DESCRIPTION
**Pull request by konklone**
This project is a document containing best practices language for government agencies to use in making clear that they are publishing **license-free data**.

This pull request takes the original **[version 1](http://razor.occams.info/pubdocs/2013-08-19_license_free.pdf)** of this document, released on August 19, 2013, and makes the following (relatively minor) changes:
- An [extended](https://github.com/unitedstates/licensing/commit/b148eb7aac9608c05d6a5fb914c344a605e0b1b2) and [rewritten](https://github.com/unitedstates/licensing/commit/0e1045608608479495ea56ee70e11f98948e19ca) introduction.
- Notes that these principles and the use of the CC0 license [apply equally well to software](https://github.com/unitedstates/licensing/commit/b0a20cb2e1e51fe534ea34a17e26e127fcaf46a8).
- Explicitly notes that [not all data is copyrightable](https://github.com/unitedstates/licensing/commit/125ca4a40b21f126acc379624658ceaa8099ce83).
- States that it's [incumbent on the agency](https://github.com/unitedstates/licensing/commit/d279af48559c6b8896bb3342d1a8220f4eed976f) to determine the intellectual property status of the open data it publishes. (Small clarification [about unclear situations](https://github.com/unitedstates/licensing/commit/96c62f4b8ae0bc5a18fc767617cfc8ef86d53137).)
- Clarifies the suggestion to [openly license non-governmental contributions](https://github.com/unitedstates/licensing/commit/1d08da93742d9930246f80cd62b52602243d9270) when mixed in with governmental publication.
- Mention [Project Open Data](http://project-open-data.github.io/) as a user of CC0 for mixed content data.
- [Tweak some However's](https://github.com/unitedstates/licensing/commit/491c51b6d0acc39f6bcb1d4de2e7240e2b36154b) in the license text (non-substantive).
- [Some small legal tweaks](https://github.com/unitedstates/licensing/pull/3/files) proposed by @thisisparker from the EFF, and [modified slightly](https://github.com/unitedstates/licensing/pull/8/files) after subsequent [dialogue below](https://github.com/unitedstates/licensing/pull/1#issuecomment-28348384).
#### [Read version 2 in full here.](https://github.com/unitedstates/licensing/blob/v2/index.md#open-government-data-best-practices-language-for-making-data-license-free)

If merged, the text will replace the v1 document currently showing at [theunitedstates.io/licensing](http://theunitedstates.io/licensing).

(**Update**: Version 2 is now live at [theunitedstates.io/licensing](http://theunitedstates.io/licensing).)

**If you or your organization would like to sign on to this document**, please comment here saying so, along with whether or not you are signing on your organization's behalf. I'll add your name/org/link to the bottom of the document before merging.

### CODE REVIEW

**Comment by mwweinberg** [comment]
I'd like to sign on to this and I'm working on getting PK proper to sign on.

**Comment by JoshData** [comment]
Hey all. [Project Open Data](http://project-open-data.github.io/) re-licensed itself so that non-gov contributors must use CC0. I've updated V2 of our doc to mention them, next to the spot where we mention WhiteHouse.gov's use of the mixed PD/CC approach.

**Comment by thisisparker** [comment]
Hi all -- EFF has proposed some edits in #3. A few of them are just typo fixes, but there is some clarification stuff added around the **For Government Works Produced By a Contractor** and **For Primary Legal Materials** sections. Shouldn't change the meaning, but let me know if you have comments.

**Comment by konklone** [comment]
Thanks, @thisisparker. @JoshData, you should check out the full diff in #3, but I think Parker's description is right that most of the changes don't change the meaning of things. I'll point out a couple I think do here, especially since Github's diff viewer is annoying for prose, 

For **Government Works Produced By a Contractor**, it changes:

> Works produced under a contract with the government are typically subject to copyright protection. If the contract provides that ownership of the work is transferred to the government, use:

to:

> Works produced under a contract with the government may be subject to copyright protection. To the extent necessary, any such contract should specify that any copyright in the work is transferred to the government. Works can then be shared with the following language:

So this is an affirmative statement that government agencies should negotiate contracts that involve an explicit transfer of IP from the contractor to the government. I'm a :+1: for this, and would be happy to see it incorporated, but obviously I've also been fine without it. We'd also need to show this to earlier signers (OKFN, CDT) and make sure they're okay with it. I'm interested to hear reactions.

It also changes `Note that not all data is copyrightable.` to `Note that most data is not copyrightable as such, though compilations of same may be copyrightable.`. I don't have an issue with that, I think it's non-substantive. 

The **Primary Legal Materials** changes just add `For avoidance of doubt` to a couple of places, seems okay to me.

Also, generally: I want to be as precise as possible with the specific recommended legal text, but I'm not sure the language prefacing and describing the recommended text needs to be held to the same standard of bulletproof-ness. I understand being cautious by nature, but the license text is what people are ultimately going to be held accountable to, not our explanations.

**Comment by JoshData** [comment]
Hey guys.

I'm all +1 on non-substantive changes. Specifically that's lines 12 (deletes "we think"), 14 (deletes "2007"), 16 ("and/or"), 39 (deletes typo "the"), and 57 (facts not copyrightable as such) in issue #3. Thanks for all of these fixes, @thisisparker. I think we can pull those all into this pull req.

On the gov contractor part: I find the change confusing. "To the extent necessary, contracts should X." That's sort of tautological isn't it? If it's _necessary_, then logically they _should_ too. So I'm -1 on this as-is.

The part about primary legal materials actually seems like a substantive change. In those cases, the materials aren't subject to domestic copyright but they are still subject to foreign copyright. So while CC0 is most importantly for the avoidance of doubt domestically, its effect is more than that. Maybe we need to tweak the text so that's clearer?

**Comment by konklone** [comment]
Just a note to everyone on the thread so far - I have some suggestions from PK in email, and @thisisparker's edits in PR (pull request) form, discussed above. I'm going to turn PK's suggestions into a PR, and then I'd like to get these discussed and merged in this week. So hopefully we can all (myself included) be pretty responsive this week in any back and forth we need to do (I don't think we'll need to do much).

Also, a couple Thursdays ago, I did a blitz of redesign work on the document's site, including adding a dynamic nav, and I've deployed it to the current live version here: [theunitedstates.io/licensing](http://theunitedstates.io/licensing/) Notice the new URL too. There might be tweaks of course, but I'm no longer describing the design as "non-final".

**Comment by konklone** [comment]
Okay, so let's see if we can reconcile @thisisparker's PR, #3.
1. On Government Contractors, @JoshData objects to adding "to the extent necessary", as tautological. I agree that it seems redundant, and would like to suggest we drop that change. 
2. Shortly before that, #3 changes "...are typically subject to copyright protection" to "may be subject to copyright protection". I like this, because it removes an implication (that this is usually the case) that I wouldn't know enough to argue about, and doesn't reduce the need to provide language to address the case where it is the case. So I think we should keep it.
3. On the Primary Legal Materials section - @JoshData, you said your issue is that these are primary legal materials that aren't covered by domestic copyright, so the waiver internationally is for more than avoidance of doubt. @thisisparker, what do you think of this, and is there some more verbose middle ground, like "For avoidance of doubt and to ensure unrestricted availability worldwide", that would suffice?
4. The other two changes in the Primary Legal Materials section are adding "expressly" before "waives" and rephrasing _"For other aspects of law that do not fall into one of the categories above"_ to _"For avoidance of doubt, if the law includes components that may not clearly"_. The first seems un-objected to. If the second one is given the same treatment as the previous item, will that suffice?

**Comment by thisisparker** [comment]
It all seems fine to me. I'm going to give an enthusiastic +½ and double-check internally.

**Comment by JoshData** [comment]
That all sounds good (incl. "For avoidance of doubt and to ensure unrestricted availability worldwide" in both places).

For "expressly", we don't have that in any of the other suggested language. I'm fine adding it to primary legal materials in case it's particularly meaningful there, but in general I'd like to keep the language uniform.

**Comment by konklone** [comment]
All right, cool. @thisisparker, let us know about the other ½ -- and, if you know, what the rationale for "expressly" is. And @joshdata, one way to make the language consistent would be to add "expressly" to the earlier language.

**Comment by konklone** [comment]
@thisisparker, any update?

**Comment by konklone** [comment]
I'm hereby relaying @mwweinberg's official :+1: on everything so far, including my proposed resolution. @thisisparker, with your word we can close this chapter.

**Comment by thisisparker** [comment]
Alright, great! I can give our :+1: too. Let's ship it.

**Comment by konklone** [comment]
And the prophecy has been fulfilled. 

I'll make and merge a brief PR with my proposed changes, merge your PR (#3 - though it's no longer auto-merge-able so I will make a copy and merge it), and then merge this one. I'll then update the bottom piece of the document with the current state of signing, and probably make a couple tangential copy tweaks to the site frame at http://theunitedstates.io/licensing/. But I'll just be merging stuff, I can take it from here -- while making PRs so you can see what's happening.

**Comment by konklone** [comment]
All right - with Sunlight, @OKFN (@jwyg), and CDT ([Joe Hall](https://twitter.com/JoeBeOne)) each giving an (offline) :+1: to stay signed on, I'm merging this in.

A bunch of signers-on will be announcing and promoting this document on the morning of Thursday, December 12th. Before then, I'll be mildly revamping how the signers are laid out (it hasn't been touched since the original PDF layout), and doing some other aesthetic tweaks, adjusting the frame of the page and adding links, etc. 

There may also be other signers-on who want to add their name to the document, but we're not changing the body of the document in any non-cosmetic way before then. 

For anyone who's going to write about the document on Thursday (or ever), I've written up a [brief history of this project and events in its life](https://github.com/unitedstates/licensing/blob/gh-pages/HISTORY.md) that might be of use.

Thanks for everyone's patience and effort! And remember that URL:

http://theunitedstates.io/licensing/

:us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us:

**Pull request merged**
