### PR TITLE
Re-do EFF submission in #3 "incorporated edits and changes after internal EFF review" after resolving merge conflict

### PR DESCRIPTION
**Pull request by konklone**
I added a link to a URL in the middle of a paragraph that @thisisparker edited, making his PR un-automatically-merge-able. This PR includes his commit, along with a commit of mine fixing that merge error (re-adding the link).

See #3, and the discussion in #1.

### CODE REVIEW

**Comment by konklone** [comment]
Since #3 was agreed on, and this is a copy with non-substantive changes, merging this one in immediately and closing #3.

**Comment by JoshData** [comment]
::dance:: :dancers: :dancer: 

I'm updating the title/descr of this pullreq just for the historical record.

**Comment by konklone** [comment]
Thanks. I updated your comment text with emoji for maximum historical precision.

**Comment by JoshData** [comment]
haha

**Pull request merged**
