### PR TITLE
Revamp sign-on section, other smaller changes

### PR DESCRIPTION
**Pull request by konklone**
PRing from a fork, so that you can visually see what I'm proposing to merge, over at this temporary URL:

http://konklone.io/licensing/

This PR does a few things related to signing:
- I've added more signed on organizations.
- I've broken out the signing section into two parts, "Authors" and "Supporters"
- I de-linked the org names for the Authors section, where it's the less important part, since the org is reflected below that in Supporters. 
- I converted it to a `<ul>` list and re-styled the section. Links for organizations are now bold, and underlined/recolored on hover.

**Question: would Authors like their names linked to anything?** I'm thinking of linking mine to my Twitter account, for instance.

And then some other things:
- I was getting some reports of the webfont I use (Average) looking totally terrible on government computers running Windows and IE 8 and 9. I've left the headers as Average, but set every other font to 11pt Times New Roman. I'm hoping this is temporary, and I'll work on [possible fixes](http://stackoverflow.com/questions/10953037/google-webfonts-render-choppy-in-chrome-on-windows) for the problem, or at least a better font.
- I added a `/v1.html` page with the first version, and linked the first History item to it.
- I added a line to the sidebar about how the document is written and supported by various people

/cc @jwyg @joshdata @thisisparker @mwweinberg

### CODE REVIEW

**Comment by konklone** [comment]
Ccing @jwyg, mis-spelled it when posting.

**Comment by JoshData** [comment]
+1.

On name linking: I'm ambivalent, but if we do that: http://razor.occams.info.

On the font: This actually makes the § symbol in our 17 USC § 105 citation look much better, too.

On /v1.html, the link 404d.

**Comment by JoshData** [comment]
Sorry one more: The "Authored and endorsed by a variety of public interest groups." link doesn't work after the heading change.

**Comment by konklone** [comment]
Fixed the /v1.html link, it needed to be a relative path, and fixed the sidebar link. Note that on v1, the table of contents will be mismatched and not fully work, because the TOC is in the layout, rather than the document. This should probably change, but it doesn't bother me for now.

I also added links for me and @joshdata.

**Pull request merged**
